apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-2-deployment
  labels:
    app: review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review-2
          image: review_service-2:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
